apiVersion: v1
kind: Service
metadata:
  name: carbide-rest-cert-manager
  namespace: {{ include "carbide-rest-cert-manager.namespace" . }}
  labels:
    {{- include "carbide-rest-cert-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.config.tlsPort }}
      name: https
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.config.insecurePort }}
      name: http
  selector:
    {{- include "carbide-rest-cert-manager.selectorLabels" . | nindent 4 }}
