# SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grpc-client-cert
  namespace: elektra-site-agent
spec:
  dnsNames:
    - elektra.elektra-site-agent.svc.cluster.local
  duration: 720h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: vault-forge-issuer
  privateKey:
    algorithm: ECDSA
    size: 384
  renewBefore: 360h0m0s
  secretName: elektra-site-agent-grpc-client-cert
  uris:
    - spiffe://forge.local/elektra-site-agent/sa/elektra-site-agent
---
