// SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.

/*
Code is generated
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/nvidia/carbide-rest/site-manager/pkg/client/clientset/versioned/typed/crds/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeForgeV1 struct {
	*testing.Fake
}

func (c *FakeForgeV1) Sites(namespace string) v1.SiteInterface {
	return &FakeSites{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeForgeV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
